"""Generate the first-party Unicode casefold module used by the web client."""

from __future__ import annotations

import json
import random
import sys
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "static" / "unicode_casefold.js"
NORMALIZATION_OUTPUT_PATH = ROOT / "static" / "unicode_normalization.js"
NORMALIZATION_CORPUS_PATH = ROOT / "tests" / "fixtures" / "unicode" / "nfkc-python-15.json"
MOBILE_OUTPUT_PATH = ROOT / "mobile" / "src" / "domain" / "generated" / "unicode15.ts"
MAX_UNICODE_SCALAR = 0x10FFFF
PYTHON_SERIES = f"{sys.version_info.major}.{sys.version_info.minor}"


def casefold_mapping() -> dict[int, str]:
    """Return every scalar whose Python casefold differs from itself."""
    return {
        code_point: folded
        for code_point in range(MAX_UNICODE_SCALAR + 1)
        if (folded := chr(code_point).casefold()) != chr(code_point)
    }


def python_strip_code_points() -> list[int]:
    """Return the scalar set used by Python str.strip for one-character strings."""
    return [
        code_point
        for code_point in range(MAX_UNICODE_SCALAR + 1)
        if chr(code_point).isspace()
    ]


def nfkc_mapping() -> dict[int, str]:
    """Return every scalar whose Python Unicode-15 NFKC differs from itself."""
    return {
        code_point: normalized
        for code_point in range(MAX_UNICODE_SCALAR + 1)
        if (normalized := unicodedata.normalize("NFKC", chr(code_point)))
        != chr(code_point)
    }


def unicode15_assigned_ranges() -> list[tuple[int, int]]:
    """Return contiguous non-Cn ranges; Cn scalars are version barriers."""
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    for code_point in range(MAX_UNICODE_SCALAR + 2):
        assigned = (
            code_point <= MAX_UNICODE_SCALAR
            and unicodedata.category(chr(code_point)) != "Cn"
        )
        if assigned and start is None:
            start = code_point
        elif not assigned and start is not None:
            ranges.append((start, code_point - 1))
            start = None
    return ranges


def normalization_corpus() -> list[dict[str, str]]:
    """Deterministic multi-scalar regression/property corpus from Python NFKC."""
    inputs = [
        "e\u0301",
        "\u00e9",
        "a\u0301\u0323",
        "\u212b\u0323",
        "\u1100\u1161",
        "\ufb03",
        "\u2163",
        "\ua7f1",
        "S",
        "\ud800",
        "\ua7f1\u0301S",
        "\u00a0\u212a\ufb00\u0345",
    ]
    randomizer = random.Random(20260805)
    pool = [
        0x0041,
        0x0065,
        0x00C5,
        0x0301,
        0x0323,
        0x0345,
        0x1100,
        0x1161,
        0x212B,
        0x212A,
        0x2163,
        0xA7F1,
        0xFB03,
        0x1C80,
        0xD800,
        0x1CCD6,
        0x10FFFF,
    ]
    for _ in range(512):
        length = randomizer.randint(2, 8)
        inputs.append(
            "".join(chr(randomizer.choice(pool)) for _ in range(length))
        )
    return [
        {"input": value, "nfkc": unicodedata.normalize("NFKC", value)}
        for value in inputs
    ]


def render_module() -> str:
    mapping = casefold_mapping()
    strip_code_points = python_strip_code_points()
    serialized = json.dumps(
        {str(code_point): folded for code_point, folded in mapping.items()},
        ensure_ascii=True,
        separators=(",", ":"),
    )
    return f'''"use strict";

// Generated by scripts/generate_unicode_casefold.py.
// Python {PYTHON_SERIES}; Unicode {unicodedata.unidata_version}; {len(mapping)} non-identity mappings.
// Do not edit: tests/test_unicode_casefold.py proves this data against Python str.casefold over every Unicode scalar.
(function exposeUnicodeCasefold(root) {{
  const CASEFOLD_MAP = Object.freeze({serialized});
  const PYTHON_STRIP_CODE_POINTS = new Set({json.dumps(strip_code_points, separators=(",", ":"))});
  const api = Object.freeze({{
    unicodeVersion: "{unicodedata.unidata_version}",
    mappingCount: {len(mapping)},
    casefoldCharacter(character) {{
      if (typeof character !== "string" || Array.from(character).length !== 1) return null;
      const key = String(character.codePointAt(0));
      return Object.prototype.hasOwnProperty.call(CASEFOLD_MAP, key) ? CASEFOLD_MAP[key] : character;
    }},
    isPythonStripCharacter(character) {{
      if (typeof character !== "string" || Array.from(character).length !== 1) return false;
      return PYTHON_STRIP_CODE_POINTS.has(character.codePointAt(0));
    }}
  }});
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.ResumeAIUnicodeCasefold = api;
}})(typeof globalThis === "object" ? globalThis : null);
'''


def render_normalization_module() -> str:
    mapping = nfkc_mapping()
    ranges = unicode15_assigned_ranges()
    serialized_mapping = json.dumps(
        {str(code_point): normalized for code_point, normalized in mapping.items()},
        ensure_ascii=True,
        separators=(",", ":"),
    )
    serialized_ranges = json.dumps(ranges, separators=(",", ":"))
    return f'''"use strict";

// Generated by scripts/generate_unicode_casefold.py.
// Python {PYTHON_SERIES}; Unicode {unicodedata.unidata_version}; {len(mapping)} non-identity NFKC mappings; {len(ranges)} assigned ranges.
// Cn scalars are explicit version barriers so newer browser Unicode data cannot normalize a scalar unassigned by the service runtime.
// Do not edit: tests/test_unicode_casefold.py proves this artifact against Python Unicode normalization data.
(function exposeUnicodeNormalization(root) {{
  const NFKC_MAP = Object.freeze({serialized_mapping});
  const ASSIGNED_RANGES = Object.freeze({serialized_ranges}.map((range) => Object.freeze(range)));
  function scalarCodePoint(character) {{
    if (typeof character !== "string" || Array.from(character).length !== 1) return null;
    return character.codePointAt(0);
  }}
  function isUnicode15Assigned(character) {{
    const codePoint = scalarCodePoint(character);
    if (codePoint === null) return false;
    let low = 0;
    let high = ASSIGNED_RANGES.length - 1;
    while (low <= high) {{
      const middle = Math.floor((low + high) / 2);
      const range = ASSIGNED_RANGES[middle];
      if (codePoint < range[0]) high = middle - 1;
      else if (codePoint > range[1]) low = middle + 1;
      else return true;
    }}
    return false;
  }}
  function normalizeNfkc(value) {{
    if (typeof value !== "string") return null;
    let output = "";
    let assignedSegment = "";
    function flushAssignedSegment() {{
      if (!assignedSegment) return true;
      try {{ output += assignedSegment.normalize("NFC"); }} catch {{ return false; }}
      assignedSegment = "";
      return true;
    }}
    for (const character of value) {{
      if (!isUnicode15Assigned(character)) {{
        if (!flushAssignedSegment()) return null;
        output += character;
        continue;
      }}
      const key = String(character.codePointAt(0));
      const mapped = Object.prototype.hasOwnProperty.call(NFKC_MAP, key) ? NFKC_MAP[key] : character;
      if (typeof mapped !== "string") return null;
      assignedSegment += mapped;
    }}
    return flushAssignedSegment() ? output : null;
  }}
  const api = Object.freeze({{
    unicodeVersion: "{unicodedata.unidata_version}",
    mappingCount: {len(mapping)},
    assignedRangeCount: {len(ranges)},
    isUnicode15Assigned,
    normalizeNfkc
  }});
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.ResumeAIUnicodeNormalization = api;
}})(typeof globalThis === "object" ? globalThis : null);
'''


def render_normalization_corpus() -> str:
    return json.dumps(
        normalization_corpus(), ensure_ascii=True, indent=2, separators=(",", ": ")
    ) + "\n"


def render_mobile_module() -> str:
    """Render Metro-compatible Unicode 15 data for the native strict parser."""
    casefold = casefold_mapping()
    normalization = nfkc_mapping()
    strip_code_points = python_strip_code_points()
    ranges = unicode15_assigned_ranges()
    serialized_casefold = json.dumps(
        {str(code_point): folded for code_point, folded in casefold.items()},
        ensure_ascii=True,
        separators=(",", ":"),
    )
    serialized_normalization = json.dumps(
        {str(code_point): normalized for code_point, normalized in normalization.items()},
        ensure_ascii=True,
        separators=(",", ":"),
    )
    serialized_strip = json.dumps(strip_code_points, separators=(",", ":"))
    serialized_ranges = json.dumps(ranges, separators=(",", ":"))
    return f'''// Generated by scripts/generate_unicode_casefold.py.
// Python {PYTHON_SERIES}; Unicode {unicodedata.unidata_version}.
// This is a first-party Metro-compatible data module. Do not edit by hand.

export const UNICODE_VERSION = "{unicodedata.unidata_version}" as const;
export const CASEFOLD_MAPPING_COUNT = {len(casefold)} as const;
export const NFKC_MAPPING_COUNT = {len(normalization)} as const;
export const ASSIGNED_RANGE_COUNT = {len(ranges)} as const;

const CASEFOLD_MAP: Readonly<Record<string, string>> = Object.freeze({serialized_casefold});
const NFKC_MAP: Readonly<Record<string, string>> = Object.freeze({serialized_normalization});
const PYTHON_STRIP_CODE_POINTS: ReadonlySet<number> = new Set({serialized_strip});
const ASSIGNED_RANGES: readonly (readonly [number, number])[] = Object.freeze(
  {serialized_ranges}.map((range) => Object.freeze(range) as readonly [number, number]),
);

const GENERATED_DATA_IS_VALID =
  UNICODE_VERSION === "15.0.0" &&
  CASEFOLD_MAPPING_COUNT === 1530 &&
  NFKC_MAPPING_COUNT === 4928 &&
  ASSIGNED_RANGE_COUNT === 707 &&
  Object.keys(CASEFOLD_MAP).length === CASEFOLD_MAPPING_COUNT &&
  Object.keys(NFKC_MAP).length === NFKC_MAPPING_COUNT &&
  ASSIGNED_RANGES.length === ASSIGNED_RANGE_COUNT;

function scalarCodePoint(character: string): number | null {{
  if (Array.from(character).length !== 1) return null;
  return character.codePointAt(0) ?? null;
}}

export function hasUnicode15Data(): boolean {{
  return GENERATED_DATA_IS_VALID;
}}

export function isUnicode15Assigned(character: string): boolean {{
  const codePoint = scalarCodePoint(character);
  if (codePoint === null) return false;
  let low = 0;
  let high = ASSIGNED_RANGES.length - 1;
  while (low <= high) {{
    const middle = Math.floor((low + high) / 2);
    const range = ASSIGNED_RANGES[middle];
    if (codePoint < range[0]) high = middle - 1;
    else if (codePoint > range[1]) low = middle + 1;
    else return true;
  }}
  return false;
}}

export function normalizeNfkcUnicode15(value: string): string | null {{
  if (!GENERATED_DATA_IS_VALID || typeof value !== "string") return null;
  let output = "";
  let assignedSegment = "";
  const flushAssignedSegment = (): boolean => {{
    if (!assignedSegment) return true;
    try {{
      output += assignedSegment.normalize("NFC");
    }} catch {{
      return false;
    }}
    assignedSegment = "";
    return true;
  }};
  for (const character of value) {{
    if (!isUnicode15Assigned(character)) {{
      if (!flushAssignedSegment()) return null;
      output += character;
      continue;
    }}
    const codePoint = scalarCodePoint(character);
    if (codePoint === null) return null;
    const key = String(codePoint);
    const mapped = Object.prototype.hasOwnProperty.call(NFKC_MAP, key) ? NFKC_MAP[key] : character;
    if (typeof mapped !== "string") return null;
    assignedSegment += mapped;
  }}
  return flushAssignedSegment() ? output : null;
}}

export function isPythonStripCharacter(character: string): boolean {{
  const codePoint = scalarCodePoint(character);
  return codePoint !== null && PYTHON_STRIP_CODE_POINTS.has(codePoint);
}}

export function casefoldCharacterUnicode15(character: string): string | null {{
  if (!GENERATED_DATA_IS_VALID || Array.from(character).length !== 1) return null;
  const codePoint = scalarCodePoint(character);
  if (codePoint === null) return null;
  const key = String(codePoint);
  return Object.prototype.hasOwnProperty.call(CASEFOLD_MAP, key) ? CASEFOLD_MAP[key] : character;
}}
'''


def main() -> None:
    OUTPUT_PATH.write_text(render_module(), encoding="utf-8")
    NORMALIZATION_OUTPUT_PATH.write_text(render_normalization_module(), encoding="utf-8")
    NORMALIZATION_CORPUS_PATH.parent.mkdir(parents=True, exist_ok=True)
    NORMALIZATION_CORPUS_PATH.write_text(render_normalization_corpus(), encoding="utf-8")
    MOBILE_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    MOBILE_OUTPUT_PATH.write_text(render_mobile_module(), encoding="utf-8")


if __name__ == "__main__":
    main()
