"""Generate the first-party Unicode casefold module used by the web client."""

from __future__ import annotations

import json
import sys
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "static" / "unicode_casefold.js"
MAX_UNICODE_SCALAR = 0x10FFFF


def casefold_mapping() -> dict[int, str]:
    """Return every scalar whose Python casefold differs from itself."""
    return {
        code_point: folded
        for code_point in range(MAX_UNICODE_SCALAR + 1)
        if (folded := chr(code_point).casefold()) != chr(code_point)
    }


def python_strip_code_points() -> list[int]:
    """Return the scalar set used by Python str.strip for one-character strings."""
    return [
        code_point
        for code_point in range(MAX_UNICODE_SCALAR + 1)
        if chr(code_point).isspace()
    ]


def render_module() -> str:
    mapping = casefold_mapping()
    strip_code_points = python_strip_code_points()
    serialized = json.dumps(
        {str(code_point): folded for code_point, folded in mapping.items()},
        ensure_ascii=True,
        separators=(",", ":"),
    )
    return f'''"use strict";

// Generated by scripts/generate_unicode_casefold.py.
// Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}; Unicode {unicodedata.unidata_version}; {len(mapping)} non-identity mappings.
// Do not edit: tests/test_unicode_casefold.py proves this data against Python str.casefold over every Unicode scalar.
(function exposeUnicodeCasefold(root) {{
  const CASEFOLD_MAP = Object.freeze({serialized});
  const PYTHON_STRIP_CODE_POINTS = new Set({json.dumps(strip_code_points, separators=(",", ":"))});
  const api = Object.freeze({{
    unicodeVersion: "{unicodedata.unidata_version}",
    mappingCount: {len(mapping)},
    casefoldCharacter(character) {{
      if (typeof character !== "string" || Array.from(character).length !== 1) return null;
      const key = String(character.codePointAt(0));
      return Object.prototype.hasOwnProperty.call(CASEFOLD_MAP, key) ? CASEFOLD_MAP[key] : character;
    }},
    isPythonStripCharacter(character) {{
      if (typeof character !== "string" || Array.from(character).length !== 1) return false;
      return PYTHON_STRIP_CODE_POINTS.has(character.codePointAt(0));
    }}
  }});
  if (typeof module === "object" && module.exports) module.exports = api;
  if (root) root.ResumeAIUnicodeCasefold = api;
}})(typeof globalThis === "object" ? globalThis : null);
'''


def main() -> None:
    OUTPUT_PATH.write_text(render_module(), encoding="utf-8")


if __name__ == "__main__":
    main()
